### ISSUE TITLE
Could Module::Build::Tiny version requirement be more conservative?

### ISSUE THREAD

**Issue by pghmcfc** [Leont/dist-zilla-plugin-modulebuildtiny#7]
Currently the plugin generates a dependency on the same version of Module::Build::Tiny that the module's author is using. Usually this is the latest and greatest version, resulting in downstream users having to update to that version. Would it not be possible to default to some reasonable version and only require a later version if the specific module needed something from that later version? This would be on a par to Dist::Zilla generating requirements for ExtUtils::MakeMaker version 6.30 by default.

The current situation is problematic because, for instance, versions of Module::Build::Tiny after 0.028 require TAP::Harness::Env, from Test-Harness 3.29. The beta release of Red Hat Enterprise Linux 7 (full release not due until later this year) is shipping with Test-Harness 3.28, so without replacing part of the vendor's perl stack, it's not possible to update Module::Build::Tiny beyond 0.028, which is "old" already :-( It's usually possible for downstreams that have to live with these restrictions to patch out the version requirement without problems, but it would be nice not to have to do that.

By the way, it's unlikely that Red Hat would respond favourably to a request to update Test-Harness because of the amount of testing they'll already have done with the current version and the next version up having some (albeit minor) API changes.

**Comment by Leont** [comment]
> But please keep in the back of your mind my request to stop the version bumping treadmill when a point of such stability is reached, however far out that may be.

I'm open to having an additional heuristic to detect the minimum version of MBT needed to build this dist, but that's a bit tricky/unrealiable (as is any heuristic). At first glance it looks something like:
* If .PL files are present in lib, require 0.039
* If using XS, require 0.036
* For a top-level module name, require 0.019
* For sharedirs 0.014

This list may grow in the future, though.

**Comment by Leont** [comment]
I've released a new version with a «version_method = conservative» argument that does pretty much what I described above. I might make it the default at some point in the future, but it would have to prove itself first.

**Comment by Leont** [comment]
This has been made the default in 0.011 :-)
